import { StyleProp, TextStyle, ViewStyle } from 'react-native';
import React from 'react';
export interface SwitchToggleProps {
    testID?: string;
    switchOn: boolean;
    onPress: () => void;
    containerStyle?: ViewStyle;
    circleStyle?: ViewStyle;
    backgroundColorOn?: string;
    backgroundColorOff?: string;
    backgroundImageOn?: React.ReactElement;
    backgroundImageOff?: React.ReactElement;
    circleColorOff?: string;
    circleColorOn?: string;
    duration?: number;
    type?: number;
    buttonText?: string;
    backTextRight?: string;
    backTextLeft?: string;
    buttonTextStyle?: StyleProp<TextStyle>;
    textRightStyle?: StyleProp<TextStyle>;
    textLeftStyle?: StyleProp<TextStyle>;
    buttonStyle?: StyleProp<ViewStyle>;
    buttonContainerStyle?: StyleProp<ViewStyle>;
    rightContainerStyle?: StyleProp<ViewStyle>;
    leftContainerStyle?: StyleProp<ViewStyle>;
    RTL?: boolean;
}
declare function SwitchToggle({ testID, switchOn, onPress, containerStyle, circleStyle, backgroundColorOn, backgroundColorOff, circleColorOn, circleColorOff, duration, backgroundImageOn, backgroundImageOff, type, buttonText, backTextRight, backTextLeft, buttonTextStyle, textRightStyle, textLeftStyle, buttonStyle, buttonContainerStyle, rightContainerStyle, leftContainerStyle, RTL, }: SwitchToggleProps): React.ReactElement;
export default SwitchToggle;
